import React, { useState, useEffect } from 'react'
import { Box, Heading, SimpleGrid } from '@chakra-ui/react'
import { Container, Loader } from 'components'
import { type Content } from 'types/content'
import { useNavigate } from 'react-router-dom'
import { getContents } from 'api/content'

const Blog = () => {
  const navigate = useNavigate()
  const [isLoading, setIsLoading] = useState(false)
  const [contents, setContents] = useState<Content[] | null>(null)

  useEffect(() => {
    fetchContents()
  }, [])

  const fetchContents = async () => {
    setIsLoading(true)
    const response = await getContents()
    setContents(response)
    setIsLoading(false)
  }

  return (
    <Container>
      <Heading>Blog</Heading>
      <Box my={2}>Content created by users, generated by AI</Box>
      {isLoading && <Loader />}
      {!isLoading && contents && (
        <SimpleGrid columns={{ base: 1, lg: 3 }} mt={12}>
          {contents.map((content) => (
            <Box
              p={6}
              backgroundColor="gray.200"
              borderRadius="xl"
              key={content._id}
              cursor="pointer"
              onClick={() => {
                navigate(`/blog/${content._id}`)
              }}
            >
              <Box fontSize="lg" fontWeight="bold">
                {content.title}
              </Box>
              <Box fontSize="sm" fontWeight="bold" color="gray.500">
                {content.category.title}
              </Box>
              <Box mt={2}>{content.content.slice(0, 64)}...</Box>
              <Box fontSize="sm" fontWeight="bold" mt={4}>
                By {content.user.name}
              </Box>
            </Box>
          ))}
        </SimpleGrid>
      )}
    </Container>
  )
}

export default Blog
